Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -140,69 +140,76 @@ jobs:
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
       - name: Quality check for SonarCloud
+        env:
+          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-               curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=sonarintegration-1_go-todo-project -o result.json
+               curl -s https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }} -o result.json
                cat result.json
                if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
                   echo "Quality gate failed."
                   exit 1
                else
                   echo "Quality gate passed."
-                  fi
-        env:
-           GITHUB_TOKEN: ${{ secrets.GHH_TOKEN }}
+               fi
+
+               failedConditions=$(jq -r '.projectStatus.conditions[] | select(.status == "ERROR") | "\(.metricKey): \(.actualValue) (threshold: \(.errorThreshold))"' result.json)
+               if [ -n "$failedConditions" ]; then
+                 echo "Failed Conditions:"
+                 echo "$failedConditions"
+               fi
 
 
-      - name: Send notification on Slack using Webhooks - Success
-        if: ${{ always() }}
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          payload: |
-            {
-              "text": "Go project built successfully."
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      # - name: Send notification on Slack using Webhooks - Success
+      #   if: ${{ always() }}
+      #   uses: slackapi/slack-github-action@v1.24.0
+      #   with:
+      #     payload: |
+      #       {
+      #         "text": "Go project built successfully."
+      #       }
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
-      - name: Send notification on Slack using Webhooks - Failure
-        if: ${{ failure() }}
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          payload: |
-            {
-              "text": "Go build failed. Please check the build logs for details."
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      # - name: Send notification on Slack using Webhooks - Failure
+      #   if: ${{ failure() }}
+      #   uses: slackapi/slack-github-action@v1.24.0
+      #   with:
+      #     payload: |
+      #       {
+      #         "text": "Go build failed. Please check the build logs for details."
+      #       }
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
-      - name: Download Code Coverage Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: coverage-out
-          path: ./coverage
+      # - name: Download Code Coverage Artifact
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     name: coverage-out
+      #     path: ./coverage
 
-      - name: Verify Code Coverage
-        run: |
-          COVERAGE=$(go tool cover -func=./coverage/coverage.out | grep total | awk '{print $3}' | sed 's/%//')
-          THRESHOLD=5.0
-          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
-            echo "Code coverage is below threshold: $COVERAGE%"
-            exit 1
-          else
-            echo "Code coverage is above threshold: $COVERAGE%"
-          fi
-      - name: Install JFrog CLI
-        run: |
-         curl -fL https://getcli.jfrog.io | sh
-         chmod +x jfrog
-         mv jfrog /usr/local/bin/
-      - name: Configure JFrog CLI
-        env:
-         ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
-         ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
-         ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
-        run: |
-         jfrog config add rt-server --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --interactive=false
-      - name: Push Artifacts to JFrog
-        run: |
-          jfrog rt u todo_app.exe gitjfrog-libs-snapshot-local/ --url=https://shubhamtodo.jfrog.io/artifactory/gotodo-go-local/ --access-token=eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJQMXBBZ19WSWNRWTZDb2pIYlFPMk1QcU1tcWlYRng2VnI2R3FWZUNsR2lrIn0.eyJzdWIiOiJqZmFjQDAxaHh0NDFqNGF3NThoMXY4N2U3d2UxNHBuL3VzZXJzL3NodWJoYW1jaGF2QGN5YmFnZS5jb20iLCJzY3AiOiJhcHBsaWVkLXBlcm1pc3Npb25zL2FkbWluIiwiYXVkIjoiKkAqIiwiaXNzIjoiamZmZUAwMWh4dDQxajRhdzU4aDF2ODdlN3dlMTRwbiIsImlhdCI6MTcxNTc1OTExNCwianRpIjoiNzNjMjRkNzgtMzc4ZC00YTdhLThiN2UtZDAxYTcwMTU4Zjc1In0.e2DMbVLertJgGOXmWWuFC_REpbHt6xTE7wGiDSYq_Y0TCMNrvuEiFND42KjqMGIepBGdvVlzzN0fkYkVapQNaHwT97NG1uDWutkhGvr6sLZsrDjhxCJk_H4Gssez2uBjf8Pea7dkAlw1M3qmWuz_7Xkb9s-C0_mUGHC97rEDUPeeGtaQ3-wDgXZUq24Ll6ABH13VYsbuNr7FsOb2J0RBWOsAWxluuADAa80NmiSAs1PQFc_vVbXVKHe_cSHDwcc6ams8bOT9AG8jFTF2gXoT7DW2Rc_21viIk6UNCWWIPEuBIIZLlEbN1MNswrBFfSQI7ovQXGmN-5LYfBf1xMJp9A
+      # - name: Verify Code Coverage
+      #   run: |
+      #     COVERAGE=$(go tool cover -func=./coverage/coverage.out | grep total | awk '{print $3}' | sed 's/%//')
+      #     THRESHOLD=5.0
+      #     if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
+      #       echo "Code coverage is below threshold: $COVERAGE%"
+      #       exit 1
+      #     else
+      #       echo "Code coverage is above threshold: $COVERAGE%"
+      #     fi
+      # - name: Install JFrog CLI
+      #   run: |
+      #    curl -fL https://getcli.jfrog.io | sh
+      #    chmod +x jfrog
+      #    mv jfrog /usr/local/bin/
+      # - name: Configure JFrog CLI
+      #   env:
+      #    ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
+      #    ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
+      #    ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
+      #   run: |
+      #    jfrog config add rt-server --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --interactive=false
+      # - name: Push Artifacts to JFrog
+      #   run: |
+      #     jfrog rt u todo_app.exe gitjfrog-libs-snapshot-local/ --url=https://shubhamtodo.jfrog.io/artifactory/gotodo-go-local/ --access-token=eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJQMXBBZ19WSWNRWTZDb2pIYlFPMk1QcU1tcWlYRng2VnI2R3FWZUNsR2lrIn0.eyJzdWIiOiJqZmFjQDAxaHh0NDFqNGF3NThoMXY4N2U3d2UxNHBuL3VzZXJzL3NodWJoYW1jaGF2QGN5YmFnZS5jb20iLCJzY3AiOiJhcHBsaWVkLXBlcm1pc3Npb25zL2FkbWluIiwiYXVkIjoiKkAqIiwiaXNzIjoiamZmZUAwMWh4dDQxajRhdzU4aDF2ODdlN3dlMTRwbiIsImlhdCI6MTcxNTc1OTExNCwianRpIjoiNzNjMjRkNzgtMzc4ZC00YTdhLThiN2UtZDAxYTcwMTU4Zjc1In0.e2DMbVLertJgGOXmWWuFC_REpbHt6xTE7wGiDSYq_Y0TCMNrvuEiFND42KjqMGIepBGdvVlzzN0fkYkVapQNaHwT97NG1uDWutkhGvr6sLZsrDjhxCJk_H4Gssez2uBjf8Pea7dkAlw1M3qmWuz_7Xkb9s-C0_mUGHC97rEDUPeeGtaQ3-wDgXZUq24Ll6ABH13VYsbuNr7FsOb2J0RBWOsAWxluuADAa80NmiSAs1PQFc_vVbXVKHe_cSHDwcc6ams8bOT9AG8jFTF2gXoT7DW2Rc_21viIk6UNCWWIPEuBIIZLlEbN1MNswrBFfSQI7ovQXGmN-5LYfBf1xMJp9A
